"""make_client_telegram_user_id_nullable

Revision ID: d68903476856
Revises: a1b2c3d4e5f6
Create Date: 2026-04-16 14:01:31.222487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd68903476856'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'telegram_user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'telegram_user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
